version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_container
    environment:
      SA_PASSWORD: "Senha123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./notas.xls:/init/notas.xls
    networks:
      - sql_network

  initdb:
    build:
      context: .
      dockerfile: Dockerfile.initdb
    depends_on:
      - sqlserver
    networks:
      - sql_network

volumes:
  sqlserver_data:

networks:
  sql_network:
    driver: bridge
    name: sql_network_teste